services:
  node-app:
    build:
      context: ./enter_data  
      dockerfile: Dockerfile  
    image: enter_data_app
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: development

