services:
  node-app:
    build:
      context: ./enter_data  
      dockerfile: Dockerfile  
    image: enter_data_app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      NODE_ENV: development
    networks:
      - app-network
  mysql: 
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - .env 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

